from authenticfeet.spiders.adidas_male import AdidasMaleSpider
from authenticfeet.spiders.adidas_female import AdidasFemaleSpider
from authenticfeet.spiders.adidas_kids import AdidasKidsSpider
from authenticfeet.spiders.nike_male import NikeMaleSpider
from authenticfeet.spiders.nike_female import NikeFemaleSpider
from authenticfeet.spiders.nike_kids import NikeKidsSpider